/// <reference types="node" />

import { Dirent, globSync as globSyncBase, readdirSync as readdirSyncBase } from "node:fs";
import { normalizePathFromString } from "../normalize-path/normalize-path.js";

export const { globSync, readdirSync } = {
	globSync(pattern, options?: unknown): Array<string | Dirent> {
		return globSyncBase(pattern, options!).map((value: string | Dirent<string>) =>
			value && typeof value === "object"
				? Object.assign(value, {
						parentPath: normalizePathFromString(value.parentPath.toString()),
					})
				: normalizePathFromString(value),
		);
	},
	readdirSync(path, options?: unknown): Array<string | Dirent> {
		return readdirSyncBase(path, options!).map((value: string | Dirent<string> | Buffer<ArrayBuffer>) =>
			value && value instanceof Dirent
				? Object.assign(value, { name: normalizePathFromString(value.name) })
				: normalizePathFromString(value.toString()),
		);
	},
} as typeof import("node:fs");

export type {
	BigIntOptions,
	BigIntStats,
	BigIntStatsFs,
	BigIntStatsListener,
	BufferEncodingOption,
	CopyOptions,
	CopySyncOptions,
	EncodingOption,
	FSWatcher,
	GlobOptions,
	GlobOptionsWithFileTypes,
	GlobOptionsWithoutFileTypes,
	MakeDirectoryOptions,
	Mode,
	NoParamCallback,
	ObjectEncodingOptions,
	OpenAsBlobOptions,
	OpenDirOptions,
	OpenMode,
	PathLike,
	PathOrFileDescriptor,
	ReadAsyncOptions,
	ReadOptions,
	ReadOptionsWithBuffer,
	ReadPosition,
	ReadSyncOptions,
	ReadVResult,
	RmDirOptions,
	RmOptions,
	StatFsOptions,
	StatOptions,
	StatSyncFn,
	StatSyncOptions,
	StatsBase,
	StatsFsBase,
	StatsListener,
	StatWatcher,
	TimeLike,
	WatchEventType,
	WatchFileOptions,
	WatchListener,
	WatchOptions,
	WatchOptionsWithBufferEncoding,
	WatchOptionsWithStringEncoding,
	WriteFileOptions,
	WriteOptions,
	WriteVResult,
} from "node:fs";

export {
	access,
	accessSync,
	appendFile,
	appendFileSync,
	chmod,
	chmodSync,
	chown,
	chownSync,
	close,
	closeSync,
	constants,
	copyFile,
	copyFileSync,
	cp,
	cpSync,
	createReadStream,
	createWriteStream,
	Dir,
	Dirent,
	exists,
	existsSync,
	fchmod,
	fchmodSync,
	fchown,
	fchownSync,
	fdatasync,
	fdatasyncSync,
	fstat,
	fstatSync,
	fsync,
	fsyncSync,
	ftruncate,
	ftruncateSync,
	futimes,
	futimesSync,
	lchmod,
	lchmodSync,
	lchown,
	lchownSync,
	link,
	linkSync,
	lstat,
	lstatSync,
	lutimes,
	lutimesSync,
	mkdir,
	mkdirSync,
	mkdtemp,
	mkdtempSync,
	open,
	openAsBlob,
	opendir,
	opendirSync,
	openSync,
	ReadStream,
	read,
	readFile,
	readFileSync,
	readlink,
	readlinkSync,
	readSync,
	readv,
	readvSync,
	realpath,
	realpathSync,
	rename,
	renameSync,
	rm,
	rmdir,
	rmdirSync,
	rmSync,
	Stats,
	StatsFs,
	stat,
	statfs,
	statfsSync,
	statSync,
	symlink,
	symlinkSync,
	truncate,
	truncateSync,
	unlink,
	unlinkSync,
	unwatchFile,
	utimes,
	utimesSync,
	WriteStream,
	watch,
	watchFile,
	write,
	writeFile,
	writeFileSync,
	writeSync,
	writev,
	writevSync,
} from "node:fs";
